services:
  db:
    image: mysql:8
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: del
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
